version: 2.1

jobs:
  build-prod:
    docker:
      - image: circleci/node:14.17.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Build Angular App
          command: npm run build -- --prod
      - run:
          name: Run Unit Tests
          command: npm run test:headless
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist
            - node_modules
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            rm -rf awscliv2.zip aws
      - run:
          name: Upload to S3
          command: |
            DIST_OUTPUT_DIR=$(find dist -maxdepth 1 -type d | awk 'NR==2')
            aws s3 sync ${DIST_OUTPUT_DIR}/browser/ s3://${S3_BUCKET_NAME} --delete

workflows:
  version: 2
  build_and_test:
    jobs:
      # - test
      - build-prod:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - master
